import type { Cause } from "./types"

// AI-generated summaries and tags for each cause
export const causes: Cause[] = [
  {
    id: "1",
    name: "Clean Water for Rural Communities",
    organization: "Water.org",
    category: "environment",
    aiSummary:
      "Providing sustainable clean water solutions to underserved rural communities through well construction and water purification systems.",
    aiTags: ["water access", "sustainability", "rural development", "health"],
    description:
      "This initiative focuses on building wells and installing water purification systems in rural areas lacking access to clean water.",
    goal: 50,
    raised: 32.5,
    donors: 156,
    location: "Kenya",
    verified: true,
    walletAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
  },
  {
    id: "2",
    name: "Education for Refugee Children",
    organization: "UNICEF",
    category: "education",
    aiSummary:
      "Delivering quality education and learning materials to refugee children displaced by conflict, ensuring continuity in their academic journey.",
    aiTags: ["refugees", "children", "literacy", "conflict zones"],
    description: "Supporting refugee children with educational resources, teachers, and safe learning environments.",
    goal: 100,
    raised: 78.3,
    donors: 342,
    location: "Jordan",
    verified: true,
    walletAddress: "0x8ba1f109551bD432803012645Ac136ddd64DBA72",
  },
  {
    id: "3",
    name: "Mobile Health Clinics",
    organization: "Doctors Without Borders",
    category: "healthcare",
    aiSummary:
      "Operating mobile medical units to provide essential healthcare services to remote and underserved populations lacking hospital access.",
    aiTags: ["medical care", "mobile clinics", "primary care", "accessibility"],
    description: "Bringing healthcare directly to communities through fully-equipped mobile medical units.",
    goal: 75,
    raised: 45.8,
    donors: 203,
    location: "Bangladesh",
    verified: true,
    walletAddress: "0x9f8f72aA9304c8B593d555F12eF6589cC3A579A2",
  },
  {
    id: "4",
    name: "Reforestation Initiative",
    organization: "One Tree Planted",
    category: "environment",
    aiSummary:
      "Large-scale tree planting program to restore degraded forests, combat climate change, and protect biodiversity in critical ecosystems.",
    aiTags: ["climate action", "biodiversity", "carbon offset", "conservation"],
    description: "Planting millions of trees to restore forests and combat climate change.",
    goal: 40,
    raised: 38.2,
    donors: 521,
    location: "Brazil",
    verified: true,
    walletAddress: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
  },
  {
    id: "5",
    name: "Food Security Program",
    organization: "World Food Programme",
    category: "poverty",
    aiSummary:
      "Combating hunger through food distribution, agricultural training, and sustainable farming practices for vulnerable communities.",
    aiTags: ["hunger relief", "agriculture", "food distribution", "sustainability"],
    description: "Providing food assistance and agricultural support to communities facing food insecurity.",
    goal: 120,
    raised: 67.4,
    donors: 289,
    location: "Ethiopia",
    verified: true,
    walletAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  },
  {
    id: "6",
    name: "Earthquake Relief Fund",
    organization: "Red Cross",
    category: "disaster",
    aiSummary:
      "Emergency response providing shelter, medical care, and essential supplies to earthquake survivors while supporting long-term recovery.",
    aiTags: ["emergency response", "disaster relief", "shelter", "medical aid"],
    description: "Immediate relief and long-term recovery support for earthquake-affected communities.",
    goal: 200,
    raised: 156.7,
    donors: 678,
    location: "Turkey",
    verified: true,
    walletAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
  },
  {
    id: "7",
    name: "Girls STEM Education",
    organization: "Code.org",
    category: "education",
    aiSummary:
      "Empowering young girls through STEM education programs, coding workshops, and mentorship to bridge the gender gap in technology.",
    aiTags: ["STEM", "gender equality", "technology", "mentorship"],
    description: "Providing STEM education and coding skills to girls in underserved communities.",
    goal: 60,
    raised: 42.1,
    donors: 234,
    location: "India",
    verified: true,
    walletAddress: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
  },
  {
    id: "8",
    name: "Mental Health Support",
    organization: "Mind Foundation",
    category: "healthcare",
    aiSummary:
      "Providing accessible mental health services, counseling, and support groups for communities with limited access to psychological care.",
    aiTags: ["mental health", "counseling", "support groups", "wellness"],
    description: "Offering mental health services and support to underserved populations.",
    goal: 45,
    raised: 28.9,
    donors: 167,
    location: "Philippines",
    verified: true,
    walletAddress: "0x514910771AF9Ca656af840dff83E8264EcF986CA",
  },
  {
    id: "9",
    name: "Ocean Cleanup Project",
    organization: "Ocean Conservancy",
    category: "environment",
    aiSummary:
      "Removing plastic waste from oceans and coastlines while promoting sustainable practices to prevent future marine pollution.",
    aiTags: ["ocean conservation", "plastic removal", "marine life", "sustainability"],
    description: "Cleaning plastic pollution from oceans and protecting marine ecosystems.",
    goal: 85,
    raised: 51.3,
    donors: 412,
    location: "Indonesia",
    verified: true,
    walletAddress: "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
  },
  {
    id: "10",
    name: "Microfinance for Women",
    organization: "Kiva",
    category: "poverty",
    aiSummary:
      "Providing small loans and financial literacy training to women entrepreneurs, enabling economic independence and community development.",
    aiTags: ["microfinance", "women empowerment", "entrepreneurship", "financial literacy"],
    description: "Supporting women entrepreneurs with microloans and business training.",
    goal: 55,
    raised: 39.6,
    donors: 198,
    location: "Uganda",
    verified: true,
    walletAddress: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
  },
  {
    id: "11",
    name: "Wildfire Recovery",
    organization: "Direct Relief",
    category: "disaster",
    aiSummary:
      "Supporting communities affected by wildfires with emergency supplies, housing assistance, and ecosystem restoration efforts.",
    aiTags: ["wildfire relief", "emergency aid", "housing", "recovery"],
    description: "Helping communities rebuild after devastating wildfires.",
    goal: 90,
    raised: 72.8,
    donors: 345,
    location: "Australia",
    verified: true,
    walletAddress: "0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE",
  },
  {
    id: "12",
    name: "Literacy Program",
    organization: "Room to Read",
    category: "education",
    aiSummary:
      "Promoting literacy through book distribution, library establishment, and reading programs for children in low-income communities.",
    aiTags: ["literacy", "books", "libraries", "reading"],
    description: "Building libraries and promoting reading skills in underserved schools.",
    goal: 35,
    raised: 26.4,
    donors: 189,
    location: "Nepal",
    verified: true,
    walletAddress: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  },
]
